import type { IdlAccounts, IdlEvents } from "@coral-xyz/anchor";
import type { Dusk } from "./types_v2.js";

export type Market = IdlAccounts<Dusk>["market"];
export type BorrowPosition = IdlAccounts<Dusk>["borrowPosition"];
export type LeveragePosition = IdlAccounts<Dusk>["leveragePosition"];
export type LeverageDelegation = IdlAccounts<Dusk>["leverageDelegation"];
export type YieldAccount = IdlAccounts<Dusk>["yieldAccount"];
export type FutarchyAuthority = IdlAccounts<Dusk>["futarchyAuthority"];
export type ReferralProfile = IdlAccounts<Dusk>["referralProfile"];
export type V2FutarchyAuthority = FutarchyAuthority;

export type HlpClosed = IdlEvents<Dusk>["hlpClosed"];
export type HlpOpened = IdlEvents<Dusk>["hlpOpened"];
export type HlpRebalanced = IdlEvents<Dusk>["hlpRebalanced"];
export type LiquidityAdded = IdlEvents<Dusk>["liquidityAdded"];
export type LiquidityRemoved = IdlEvents<Dusk>["liquidityRemoved"];
export type MarketCollateralDeposited = IdlEvents<Dusk>["marketCollateralDeposited"];
export type MarketCollateralWithdrawn = IdlEvents<Dusk>["marketCollateralWithdrawn"];
export type MarketCreated = IdlEvents<Dusk>["marketCreated"];
export type MarketDebtUpdated = IdlEvents<Dusk>["marketDebtUpdated"];
export type MarketFeeLiabilityClaimed = IdlEvents<Dusk>["marketFeeLiabilityClaimed"];
export type MarketHealthUpdated = IdlEvents<Dusk>["marketHealthUpdated"];
export type MarketUpdated = IdlEvents<Dusk>["marketUpdated"];
export type PositionLiquidated = IdlEvents<Dusk>["positionLiquidated"];
export type ProtocolAuctionSettled = IdlEvents<Dusk>["protocolAuctionSettled"];
export type ReferralFeesClaimed = IdlEvents<Dusk>["referralFeesClaimed"];
export type ReferralOriginationFeePaid = IdlEvents<Dusk>["referralOriginationFeePaid"];
export type ReferralOriginationFeeUpdated = IdlEvents<Dusk>["referralOriginationFeeUpdated"];
export type ReferralRecipientUpdated = IdlEvents<Dusk>["referralRecipientUpdated"];
export type SwapExecuted = IdlEvents<Dusk>["swapExecuted"];
export type YieldClaimed = IdlEvents<Dusk>["yieldClaimed"];
export type YieldRecipientUpdated = IdlEvents<Dusk>["yieldRecipientUpdated"];
